server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
          filters:
            - StripPrefix=2
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**
          filters:
            - StripPrefix=2
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/transaction/**
          filters:
            - StripPrefix=2
        - id: dispensing-service
          uri: lb://dispensing-service
          predicates:
            - Path=/api/dispensing/**
          filters:
            - StripPrefix=2
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notification/**
          filters:
            - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include: health,gateway
      base-path: /actuator
  endpoint:
    gateway:
      access: read-only
    health:
      access: read-only
