spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

logging:
  level:
    com.vendingmachine.gateway.security: DEBUG
    org.springframework.security.web: INFO

server:
  port: 8080
